# Generated by Django 5.0.2 on 2024-02-22 02:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=224)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000000000)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('sold_quantity', models.IntegerField()),
            ],
        ),
    ]
